### PR TITLE
Errors Corrected and Added Links

### PR DESCRIPTION
**Pull request by vachhanihpavan**
There was NoMethodError coming up on new article creation. It is solved by adding new method in articles controller. 
Also added some links to edit, delete articles. 
Added link to all Articles on welcome page

### CODE REVIEW

**Comment by beydogan** [comment]
@vachhanihpavan thank you for the pull request, I'm little bit surprised though :) I added a review, just a typo, let me know if you can fix that and push, then I can merge the PR.

**Comment by vachhanihpavan** [comment]
Actually I'm a noobie to open source contribution. So, I was trying some pull requests.:)
Thanks for replying....
I didn't understand what you want me to fix. 
Thanks again.

**Comment by beydogan** [comment]
There is a typo on word `developed` in sentence; **This is a simple Blog application develpoed using Ruby on Rails.** in readme file.

**Comment by beydogan** [comment]
Thank you @vachhanihpavan

**Pull request merged**
